.TH ANTENNAVIS 1 "March 1, 2006" "0.3"

.SH NAME
antennavis \- Antenna Radiation Pattern Visualization Software
.SH SYNOPSIS
.B antennavis

.SH DESCRIPTION
\fBAntennavis\fP lets the user fly around and view antenna systems
and their patterns from any angle in 3D. There are several means of 
viewing the patterns, through rendered, variable-size cubes, smooth 
shaded polygonal surface approximations, and color-mapped spheres.

\fBAntennavis\fP works together with nec2. Nec2 simulates the
electromagnetic response of antennas and metal structures and can be called
from within antennavis. \fBAntennavis\fP then uses the \fBTkAnt\fP
OpenGL widget to render the nec output.

.SH AUTHORS
The program was originally developed by Kenneth Harker WM5R and Adrian Agogino.\fB
It is currently maintained by Nanakos Chrysostomos, nanakos@wired-net.gr.
